version: '3.7'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes: 
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local

